name: Continuous Integration

on:
  - workflow_dispatch
  - pull_request:
    branches: [main]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Prettier
        working-directory: ./frontend
        run: npx prettier --check
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Gofmt
        working-directory: ./backend
        run: gofmt -l **/*.go
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Backend Tests
        env:
          SUPERTOKENS_URI: ${{ secrets.TEST_SUPERTOKENS_URI }}
          SUPERTOKENS_API_KEY: ${{ secrets.TEST_SUPERTOKENS_API_KEY }}
          SUPERTOKENS_DASHBOARD_KEY: ${{ secrets.TEST_SUPERTOKENS_DASHBOARD_KEY }}
        run: docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        # uses: actions/setup-node@v3
        # with:
        #   node-version: 18.x
        working-directory: ./frontend
        run: npm install
      - name: Frontend Tests
        run: npm test
