services:
  postgres_dev:
    image: postgres:latest
    container_name: postgres_dev_container
    environment:
      - POSTGRES_USER=${DEV_DB_USER}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
      - POSTGRES_DB=${DEV_DB_NAME}
      - DATABASE_HOST=${DEV_DB_HOST}
    ports:
      - '1234:5432'
    volumes:
      - ./pg_data_dev:/var/lib/postgresql/data

  postgres_test:
    image: postgres:latest
    container_name: postgres_test_container
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - '4567:5432'
    volumes:
      - ./pg_data_test:/var/lib/postgresql/data

volumes:
  pg_data_dev:
  pg_data_test:

