name: Continuous Integration

on:
  - pull_request
  - workflow_dispatch

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Frontend Linting
        working-directory: frontend
        run: npx prettier --check .
      - name: Backend Linting
        working-directory: backend
        run: npx prettier --check .
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup Postgres
        run: docker compose up -d
      - name: Npm Install
        working-directory: backend
        run: npm install
      - name: Test
        env:
          SUPERTOKENS_URI: ${{ secrets.TEST_SUPERTOKENS_URI }}
          SUPERTOKENS_API_KEY: ${{ secrets.TEST_SUPERTOKENS_API_KEY }}
        working-directory: backend
        run: npm test
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Frontend Tests
        working-directory: frontend
        run: npm install && npm test
